REPORTS_DIR: "./reports"
ROSTERS_DIR: "./rosters"
LOGS_DIR: "./logs"
REPORT_NAME_FIELD: "Name (original name)"
REPORT_EMAIL_FIELD: "Email"
ROSTER_LAST_NAME_FIELD: "Last"
ROSTER_FIRST_NAME_FIELD: "First"
ROSTER_EMAIL_FIELD: "Email"
FILENAME_PREFIX_LENGTH: 2
